// examples/demo/react/src/components/ThemeSwitch.tsx
import React, { useState } from 'react';
import { Select } from '@tigercat/react';
import { themes, applyTheme } from '../../../shared/themes';

const ThemeSwitch: React.FC = () => {
  const [currentTheme, setCurrentTheme] = useState('default');

  const handleThemeChange = (
    value: string | number | (string | number)[] | undefined
  ) => {
    const themeValue = String(value);
    setCurrentTheme(themeValue);
    applyTheme(themeValue);
  };

  const themeOptions = themes.map((t) => ({ label: t.name, value: t.value }));

  return (
    <div className="flex items-center gap-2 shrink-0">
      <span className="text-sm font-medium text-gray-700 whitespace-nowrap shrink-0">
        主题：
      </span>
      <Select
        value={currentTheme}
        onChange={handleThemeChange}
        options={themeOptions}
        size="sm"
        className="w-40 max-w-full"
      />
    </div>
  );
};

export default ThemeSwitch;

// examples/demo/vue3/src/components/ThemeSwitch.vue
<script setup lang="ts">
import { ref } from 'vue'
import { Select } from '@tigercat/vue'
import { themes, applyTheme } from '../../../shared/themes'

const currentTheme = ref('default')

const handleThemeChange = (value: string) => {
  currentTheme.value = value
  applyTheme(value)
}

const themeOptions = themes.map(t => ({ label: t.name, value: t.value }))
</script>

<template>
  <div class="flex items-center gap-2 shrink-0">
    <span class="text-sm font-medium text-gray-700 whitespace-nowrap shrink-0">主题：</span>
    <Select 
      :model-value="currentTheme"
      @update:model-value="handleThemeChange"
      :options="themeOptions"
      size="sm"
      class="w-40 max-w-full"
    />
  </div>
</template>
