// examples/example/vue3/src/pages/CalendarDemo.vue
<script setup lang="ts">
import DemoPage from '../components/DemoPage.vue'
import { getDemoModules } from '../playground/registry'

// CalendarDemo
const modules = getDemoModules('calendar')
</script>

<template>
  <DemoPage
    title="Calendar 日历"
    description="按月/年展示日期的日历面板，支持日期选择和禁用。"
    :modules="modules" />
</template>

// examples/example/react/src/pages/CalendarDemo.tsx
import DemoPage from '../components/DemoPage'
import { getDemoModules } from '../playground/registry'

const modules = getDemoModules('calendar')

export default function CalendarDemo() {
  return (
    <DemoPage
      title="Calendar 日历"
      description="按月/年展示日期的日历面板，支持日期选择和禁用。"
      modules={modules}
    />
  )
}
