// examples/example/vue3/src/pages/FloatButtonDemo.vue
<template>
  <div class="max-w-5xl mx-auto p-4 sm:p-8">
    <h1 class="text-3xl font-bold mb-2">FloatButton 悬浮按钮</h1>
    <p class="text-gray-500 mb-8">悬浮在页面角落的操作按钮，支持分组展开。</p>

    <DemoBlock
      title="基础用法等组合展示"
      description="合并展示基础用法、按钮组、禁用，减少重复示例块。"
      :code="fullPageSnippet">
      <div class="space-y-6">
        <div class="space-y-3">
          <h3 class="text-sm font-semibold text-gray-700 dark:text-gray-200">基础用法</h3>
          <div class="relative h-64 border rounded-lg overflow-hidden">
            <FloatButton
              tooltip="默认"
              style="position: absolute; right: 24px; bottom: 24px"
              @click="onClick" />
            <FloatButton
              shape="square"
              type="default"
              tooltip="方形"
              style="position: absolute; right: 24px; bottom: 80px" />
            <FloatButton
              size="lg"
              tooltip="大号"
              style="position: absolute; right: 24px; bottom: 136px" />
          </div>
        </div>
        <div class="space-y-3">
          <h3 class="text-sm font-semibold text-gray-700 dark:text-gray-200">按钮组</h3>
          <div class="relative h-64 border rounded-lg overflow-hidden">
            <FloatButtonGroup trigger="hover" style="position: absolute; right: 24px; bottom: 24px">
              <template #trigger>
                <FloatButton tooltip="菜单" />
              </template>
              <FloatButton tooltip="操作 A" type="default" />
              <FloatButton tooltip="操作 B" type="default" />
            </FloatButtonGroup>
          </div>
        </div>
        <div class="space-y-3">
          <h3 class="text-sm font-semibold text-gray-700 dark:text-gray-200">禁用</h3>
          <div class="relative h-40 border rounded-lg overflow-hidden">
            <FloatButton
              disabled
              tooltip="不可用"
              style="position: absolute; right: 24px; bottom: 24px" />
          </div>
        </div>
      </div>
    </DemoBlock>

    <DemoBlock
      title="独立悬浮"
      description="单个 FloatButton 可直接固定到视口角落。"
      :code="fullPageSnippet">
      <FloatButton
        floating
        placement="bottom-right"
        :offset="24"
        tooltip="客服"
        aria-label="客服入口" />
    </DemoBlock>
  </div>
</template>

<script setup lang="ts">
import { FloatButton } from '@expcat/tigercat-vue/FloatButton'
import { FloatButtonGroup } from '@expcat/tigercat-vue/FloatButtonGroup'
import DemoBlock from '../components/DemoBlock.vue'
import fullPageSnippet from './FloatButtonDemo.vue?raw'

const onClick = () => {
  console.log('FloatButton clicked')
}

const basicSnippet = `<FloatButton tooltip="默认" @click="onClick" />
<FloatButton shape="square" type="default" tooltip="方形" />
<FloatButton size="lg" tooltip="大号" />`

const groupSnippet = `<FloatButtonGroup trigger="hover">
  <template #trigger>
    <FloatButton tooltip="菜单" />
  </template>
  <FloatButton tooltip="操作 A" type="default" />
  <FloatButton tooltip="操作 B" type="default" />
</FloatButtonGroup>`

const disabledSnippet = `<FloatButton disabled tooltip="不可用" />`

const floatingSnippet = `<FloatButton
  floating
  placement="bottom-right"
  :offset="24"
  tooltip="客服"
  aria-label="客服入口"
/>`
</script>

// examples/example/react/src/pages/FloatButtonDemo.tsx
import { FloatButton } from '@expcat/tigercat-react/FloatButton'
import { FloatButtonGroup } from '@expcat/tigercat-react/FloatButtonGroup'
import DemoBlock from '../components/DemoBlock'
import fullPageSnippet from './FloatButtonDemo.tsx?raw'

const basicSnippet = `<FloatButton tooltip="默认" onClick={() => console.log('clicked')} />
<FloatButton shape="square" type="default" tooltip="方形" />
<FloatButton size="lg" tooltip="大号" />`

const groupSnippet = `<FloatButtonGroup trigger="hover" triggerNode={<FloatButton tooltip="菜单" />}>
  <FloatButton tooltip="操作 A" type="default" />
  <FloatButton tooltip="操作 B" type="default" />
</FloatButtonGroup>`

const disabledSnippet = `<FloatButton disabled tooltip="不可用" />`

const floatingSnippet = `<FloatButton
  floating
  placement="bottom-right"
  offset={24}
  tooltip="客服"
  ariaLabel="客服入口"
/>`

const FloatButtonDemo: React.FC = () => {
  return (
    <div className="max-w-5xl mx-auto p-4 sm:p-8">
      <h1 className="text-3xl font-bold mb-2">FloatButton 悬浮按钮</h1>
      <p className="text-gray-500 mb-8">悬浮在页面角落的操作按钮，支持分组展开。</p>

      <DemoBlock
        title="基础用法等组合展示"
        description="合并展示基础用法、按钮组、禁用，减少重复示例块。"
        code={fullPageSnippet}>
        <div className="space-y-6">
          <div className="space-y-3">
            <h3 className="text-sm font-semibold text-gray-700 dark:text-gray-200">基础用法</h3>
            <div className="relative h-64 border rounded-lg overflow-hidden">
              <FloatButton
                tooltip="默认"
                style={{ position: 'absolute', right: 24, bottom: 24 }}
                onClick={() => console.log('clicked')}
              />
              <FloatButton
                shape="square"
                type="default"
                tooltip="方形"
                style={{ position: 'absolute', right: 24, bottom: 80 }}
              />
              <FloatButton
                size="lg"
                tooltip="大号"
                style={{ position: 'absolute', right: 24, bottom: 136 }}
              />
            </div>
          </div>
          <div className="space-y-3">
            <h3 className="text-sm font-semibold text-gray-700 dark:text-gray-200">按钮组</h3>
            <div className="relative h-64 border rounded-lg overflow-hidden">
              <FloatButtonGroup
                trigger="hover"
                triggerNode={<FloatButton tooltip="菜单" />}
                style={{ position: 'absolute', right: 24, bottom: 24 }}>
                <FloatButton tooltip="操作 A" type="default" />
                <FloatButton tooltip="操作 B" type="default" />
              </FloatButtonGroup>
            </div>
          </div>
          <div className="space-y-3">
            <h3 className="text-sm font-semibold text-gray-700 dark:text-gray-200">禁用</h3>
            <div className="relative h-40 border rounded-lg overflow-hidden">
              <FloatButton
                disabled
                tooltip="不可用"
                style={{ position: 'absolute', right: 24, bottom: 24 }}
              />
            </div>
          </div>
        </div>
      </DemoBlock>

      <DemoBlock
        title="独立悬浮"
        description="单个 FloatButton 可直接固定到视口角落。"
        code={fullPageSnippet}>
        <FloatButton
          floating
          placement="bottom-right"
          offset={24}
          tooltip="客服"
          ariaLabel="客服入口"
        />
      </DemoBlock>
    </div>
  )
}

export default FloatButtonDemo
