// examples/example/vue3/src/pages/FormWizardDemo.vue
<script setup lang="ts">
import { reactive, ref } from 'vue'
import { FormWizard, Form, FormItem, Input, Alert } from '@expcat/tigercat-vue'
import type { WizardStep } from '@expcat/tigercat-core'
import DemoBlock from '../components/DemoBlock.vue'

const steps: WizardStep[] = [
  { title: '基本信息', description: '填写姓名与邮箱' },
  { title: '联系方式', description: '填写手机号' },
  { title: '完成', description: '提交并确认' }
]

const current = ref(0)
const finished = ref(false)
const formRef = ref<InstanceType<typeof Form> | null>(null)
const model = reactive({ name: '', email: '', phone: '' })

const handleBeforeNext = async () => {
  const valid = await formRef.value?.validate()
  if (!valid) {
    return '请先完成当前步骤校验'
  }
  return true
}

const handleFinish = () => {
  finished.value = true
}

const handleChange = () => {
  finished.value = false
}

const basicSnippet = `<FormWizard
  v-model:current="current"
  :steps="steps"
  :before-next="handleBeforeNext"
  @change="handleChange"
  @finish="handleFinish">
  <template #step="{ index }">
    <Form ref="formRef" :model="model" class="max-w-xl">
      <template v-if="index === 0">
        <FormItem name="name" label="姓名" :rules="{ required: true, message: '请输入姓名' }">
          <Input v-model="model.name" placeholder="请输入姓名" />
        </FormItem>
        <FormItem name="email" label="邮箱" :rules="{ required: true, message: '请输入邮箱' }">
          <Input v-model="model.email" placeholder="请输入邮箱" />
        </FormItem>
      </template>
      <template v-else-if="index === 1">
        <FormItem name="phone" label="手机号" :rules="{ required: true, message: '请输入手机号' }">
          <Input v-model="model.phone" placeholder="请输入手机号" />
        </FormItem>
      </template>
      <template v-else>
        <div class="space-y-3">
          <div class="text-sm text-gray-600">确认信息无误后点击完成。</div>
          <Alert :type="finished ? 'success' : 'info'" :description="finished ? '已完成提交' : '等待完成提交'" />
        </div>
      </template>
    </Form>
  </template>
</FormWizard>`
</script>

<template>
  <div class="max-w-6xl mx-auto p-8">
    <div class="mb-8">
      <h1 class="text-3xl font-bold mb-2">FormWizard 表单向导</h1>
      <p class="text-gray-600">多步表单流，支持校验阻断与完成态。</p>
    </div>

    <DemoBlock title="基础用法" description="多步校验阻断 + 完成态" :code="basicSnippet">
      <FormWizard
        v-model:current="current"
        :steps="steps"
        :before-next="handleBeforeNext"
        @change="handleChange"
        @finish="handleFinish">
        <template #step="{ index }">
          <Form ref="formRef" :model="model" class="max-w-xl">
            <template v-if="index === 0">
              <FormItem name="name" label="姓名" :rules="{ required: true, message: '请输入姓名' }">
                <Input v-model="model.name" placeholder="请输入姓名" />
              </FormItem>
              <FormItem name="email" label="邮箱" :rules="{ required: true, message: '请输入邮箱' }">
                <Input v-model="model.email" placeholder="请输入邮箱" />
              </FormItem>
            </template>
            <template v-else-if="index === 1">
              <FormItem name="phone" label="手机号" :rules="{ required: true, message: '请输入手机号' }">
                <Input v-model="model.phone" placeholder="请输入手机号" />
              </FormItem>
            </template>
            <template v-else>
              <div class="space-y-3">
                <div class="text-sm text-gray-600">确认信息无误后点击完成。</div>
                <Alert
                  :type="finished ? 'success' : 'info'"
                  :description="finished ? '已完成提交' : '等待完成提交'" />
              </div>
            </template>
          </Form>
        </template>
      </FormWizard>
    </DemoBlock>
  </div>
</template>

// examples/example/react/src/pages/FormWizardDemo.tsx
import React, { useMemo, useRef, useState } from 'react'
import {
  FormWizard,
  Form,
  FormItem,
  Input,
  Alert,
  type FormHandle,
  type WizardStep
} from '@expcat/tigercat-react'
import DemoBlock from '../components/DemoBlock'

const basicSnippet = `<FormWizard
  steps={steps}
  current={current}
  onChange={setCurrent}
  beforeNext={handleBeforeNext}
  onFinish={handleFinish}
  renderStep={(_step, index) => (
    <Form ref={formRef} model={model} className="max-w-xl">
      {index === 0 && (
        <>
          <FormItem name="name" label="姓名" rules={{ required: true, message: '请输入姓名' }}>
            <Input value={model.name} onChange={(e) => setModel((prev) => ({ ...prev, name: e.target.value }))} />
          </FormItem>
          <FormItem name="email" label="邮箱" rules={{ required: true, message: '请输入邮箱' }}>
            <Input value={model.email} onChange={(e) => setModel((prev) => ({ ...prev, email: e.target.value }))} />
          </FormItem>
        </>
      )}
      {index === 1 && (
        <FormItem name="phone" label="手机号" rules={{ required: true, message: '请输入手机号' }}>
          <Input value={model.phone} onChange={(e) => setModel((prev) => ({ ...prev, phone: e.target.value }))} />
        </FormItem>
      )}
      {index === 2 && (
        <div className="text-sm text-gray-600">确认信息无误后点击完成。</div>
      )}
    </Form>
  )}
/>`

const FormWizardDemo: React.FC = () => {
  const steps = useMemo<WizardStep[]>(
    () => [
      { title: '基本信息', description: '填写姓名与邮箱' },
      { title: '联系方式', description: '填写手机号' },
      { title: '完成', description: '提交并确认' }
    ],
    []
  )

  const [current, setCurrent] = useState(0)
  const [model, setModel] = useState({ name: '', email: '', phone: '' })
  const [finished, setFinished] = useState(false)
  const formRef = useRef<FormHandle | null>(null)

  const handleBeforeNext = async () => {
    const valid = await formRef.current?.validate()
    if (!valid) {
      return '请先完成当前步骤校验'
    }
    return true
  }

  const handleFinish = () => {
    setFinished(true)
  }

  return (
    <div className="max-w-6xl mx-auto p-8">
      <div className="mb-8">
        <h1 className="text-3xl font-bold mb-2">FormWizard 表单向导</h1>
        <p className="text-gray-600">多步表单流，支持校验阻断与完成态。</p>
      </div>

      <DemoBlock title="基础用法" description="多步校验阻断 + 完成态" code={basicSnippet}>
        <FormWizard
          steps={steps}
          current={current}
          onChange={(next) => {
            setFinished(false)
            setCurrent(next)
          }}
          beforeNext={handleBeforeNext}
          onFinish={handleFinish}
          renderStep={(_step, index) => (
            <Form ref={formRef} model={model} className="max-w-xl">
              {index === 0 && (
                <>
                  <FormItem name="name" label="姓名" rules={{ required: true, message: '请输入姓名' }}>
                    <Input
                      value={model.name}
                      onChange={(event) =>
                        setModel((prev) => ({ ...prev, name: event.target.value }))
                      }
                      placeholder="请输入姓名"
                    />
                  </FormItem>
                  <FormItem name="email" label="邮箱" rules={{ required: true, message: '请输入邮箱' }}>
                    <Input
                      value={model.email}
                      onChange={(event) =>
                        setModel((prev) => ({ ...prev, email: event.target.value }))
                      }
                      placeholder="请输入邮箱"
                    />
                  </FormItem>
                </>
              )}
              {index === 1 && (
                <FormItem name="phone" label="手机号" rules={{ required: true, message: '请输入手机号' }}>
                  <Input
                    value={model.phone}
                    onChange={(event) =>
                      setModel((prev) => ({ ...prev, phone: event.target.value }))
                    }
                    placeholder="请输入手机号"
                  />
                </FormItem>
              )}
              {index === 2 && (
                <div className="space-y-3">
                  <div className="text-sm text-gray-600">确认信息无误后点击完成。</div>
                  {finished ? (
                    <Alert type="success" description="已完成提交" />
                  ) : (
                    <Alert type="info" description="等待完成提交" />
                  )}
                </div>
              )}
            </Form>
          )}
        />
      </DemoBlock>
    </div>
  )
}

export default FormWizardDemo
