// examples/example/vue3/src/pages/UseControlledStateDemo.vue
<script setup lang="ts">
import { computed, defineComponent, h, ref } from 'vue'
import { Alert } from '@expcat/tigercat-vue/Alert'
import { Button } from '@expcat/tigercat-vue/Button'
import { Card } from '@expcat/tigercat-vue/Card'

const Counter = defineComponent({
  name: 'DemoCounter',
  props: {
    modelValue: { type: Number, default: undefined },
    defaultValue: { type: Number, default: 0 }
  },
  emits: ['update:modelValue'],
  setup(props, { emit }) {
    const inner = ref(props.defaultValue)
    const isControlled = computed(() => props.modelValue !== undefined)
    const count = computed(() => (isControlled.value ? (props.modelValue as number) : inner.value))

    function commit(next: number) {
      if (!isControlled.value) inner.value = next
      emit('update:modelValue', next)
    }

    return () =>
      h('div', { class: 'flex items-center gap-3' }, [
        h(Button, { onClick: () => commit(count.value - 1) }, () => '-'),
        h('span', { class: 'w-8 text-center font-medium' }, String(count.value)),
        h(Button, { onClick: () => commit(count.value + 1) }, () => '+')
      ])
  }
})

const controlledCount = ref(5)
</script>

<template>
  <div class="max-w-5xl mx-auto p-4 sm:p-8">
    <div class="mb-8">
      <h1 class="text-3xl font-bold mb-2">useControlledState</h1>
      <p class="text-gray-600 dark:text-gray-400">
        React 独有 hook。Vue 没有导出 composable，但受控哨兵同一句：
        <code>undefined</code> 非受控，<code>null</code> 是合法空值。
      </p>
    </div>

    <Alert
      type="info"
      message="Vue 不导出这份 hook"
      description="v-model 只是语法糖。省略 modelValue 才是非受控；把默认写成 null 或用 ?? 会把合法空值当成缺省。下面两块 Counter 用同一套哨兵。" />

    <Card title="受控" class="mt-6">
      <Counter v-model="controlledCount" />
    </Card>

    <Card title="非受控" class="mt-6">
      <Counter :default-value="0" />
    </Card>

    <Card title="哨兵" class="mt-6">
      <pre
        class="text-sm overflow-x-auto bg-gray-50 p-4 rounded"><code>const isControlled = computed(() => props.modelValue !== undefined)
const inner = ref(props.defaultValue ?? 0)
const value = computed(() =>
  isControlled.value ? props.modelValue : inner.value
)
function commit(next: number) {
  if (!isControlled.value) inner.value = next
  emit('update:modelValue', next)
}</code></pre>
    </Card>
  </div>
</template>

// examples/example/react/src/pages/UseControlledStateDemo.tsx
import React, { useState } from 'react'
import { useControlledState, Button, Space, Card } from '@expcat/tigercat-react'
import DemoBlock from '../components/DemoBlock'

interface CounterProps {
  value?: number
  defaultValue?: number
  onChange?: (next: number) => void
}

const Counter: React.FC<CounterProps> = ({ value, defaultValue = 0, onChange }) => {
  const [count, setCount, isControlled] = useControlledState<number>(value, defaultValue)

  const update = (next: number) => {
    if (!isControlled) setCount(next)
    onChange?.(next)
  }

  return (
    <Space>
      <Button onClick={() => update(count - 1)}>-</Button>
      <span className="w-10 text-center text-base font-medium">{count}</span>
      <Button onClick={() => update(count + 1)}>+</Button>
      <span className="text-xs text-gray-500">{isControlled ? '受控' : '非受控'}</span>
    </Space>
  )
}

const snippet = `import { useControlledState } from '@expcat/tigercat-react'

interface CounterProps {
  value?: number
  defaultValue?: number
  onChange?: (next: number) => void
}

const Counter: React.FC<CounterProps> = ({ value, defaultValue = 0, onChange }) => {
  const [count, setCount, isControlled] = useControlledState<number>(value, defaultValue)

  const update = (next: number) => {
    if (!isControlled) setCount(next)
    onChange?.(next)
  }

  return (
    <button onClick={() => update(count + 1)}>{count}</button>
  )
}`

const UseControlledStateDemo: React.FC = () => {
  const [external, setExternal] = useState(10)

  return (
    <div className="max-w-5xl mx-auto p-8">
      <div className="mb-8">
        <h1 className="text-3xl font-bold mb-2">useControlledState 受控/非受控</h1>
        <p className="text-gray-600">
          统一处理表单组件「受控 / 非受控」两种用法的样板代码，避免重复 if/else。
        </p>
      </div>

      <DemoBlock
        title="非受控模式"
        description="只传入 defaultValue，组件内部维护状态。"
        code={snippet}>
        <Card>
          <Counter defaultValue={5} />
        </Card>
      </DemoBlock>

      <DemoBlock
        title="受控模式"
        description="传入 value 与 onChange，由父组件控制状态。"
        code={snippet}>
        <Card>
          <Counter value={external} onChange={setExternal} />
          <div className="mt-3 text-sm text-gray-500">
            外部状态：<strong>{external}</strong>
          </div>
        </Card>
      </DemoBlock>
    </div>
  )
}

export default UseControlledStateDemo
