// examples/example/vue3/src/pages/WorkflowDesignerDemo.vue
<script setup lang="ts">
import DemoPage from '../components/DemoPage.vue'
import { getDemoModules } from '../playground/registry'

const modules = getDemoModules('workflow-designer')
</script>

<template>
  <DemoPage
    title="WorkflowDesigner 流程设计器"
    description="简单 JSON 树流程编辑器。复用 WorkflowTimelineStep，可选子路径编辑。不是 BPMN。"
    :modules="modules" />
</template>

// examples/example/react/src/pages/WorkflowDesignerDemo.tsx
import DemoPage from '../components/DemoPage'
import { getDemoModules } from '../playground/registry'

const modules = getDemoModules('workflow-designer')

export default function WorkflowDesignerDemo() {
  return (
    <DemoPage
      title="WorkflowDesigner 流程设计器"
      description="简单 JSON 树流程编辑器。复用 WorkflowTimelineStep，可选子路径编辑。不是 BPMN。"
      modules={modules}
    />
  )
}
