// examples/example/vue3/src/components/DemoBlock.vue
<script setup lang="ts">
import { computed, inject, onBeforeUnmount, onMounted, ref, watch, type Ref } from 'vue'
import { Button } from '@expcat/tigercat-vue/Button'
import { CodeEditor } from '@expcat/tigercat-vue/CodeEditor'
import { copyTextToClipboard, ThemeManager } from '@expcat/tigercat-core'
import { collectTigerCssVars } from '@demo-shared/themes'
import runtimeUrlsValue from 'virtual:tigercat-playground-runtime'
import type { DemoLang } from '@demo-shared/app-config'
import { demoChrome, demoModuleTitle } from '@demo-shared/chrome'
import { resolveDemoViewport } from '@demo-shared/playground/viewport'
import type {
  DemoCompileResponse,
  DemoCompileSuccess,
  DemoDiagnostic,
  DemoModuleDescriptor,
  DemoSourceBundle
} from '@demo-shared/playground/types'
import {
  createSandboxDocument,
  getSandboxAttribute,
  isSandboxEvent
} from '@demo-shared/playground/sandbox'
import stylesheetUrl from '@demo-shared/sandbox.css?url'

const props = defineProps<{
  module: DemoModuleDescriptor
  class?: string
}>()

interface ConsoleEntry {
  level: string
  message: string
}

let compilerWorker: Worker | null = null
let nextRequestId = 1
const pendingCompiles = new Map<
  number,
  { resolve: (result: DemoCompileSuccess) => void; reject: (diagnostics: DemoDiagnostic[]) => void }
>()

function getCompilerWorker(): Worker {
  if (compilerWorker) return compilerWorker
  compilerWorker = new Worker(new URL('../playground/compiler.worker.ts', import.meta.url), {
    type: 'module'
  })
  compilerWorker.onmessage = (event: MessageEvent<DemoCompileResponse>) => {
    const pending = pendingCompiles.get(event.data.requestId)
    if (!pending) return
    pendingCompiles.delete(event.data.requestId)
    if (event.data.type === 'compiled') pending.resolve(event.data)
    else pending.reject(event.data.diagnostics)
  }
  return compilerWorker
}

function compileBundle(bundle: DemoSourceBundle): Promise<DemoCompileSuccess> {
  const requestId = nextRequestId++
  return new Promise((resolve, reject) => {
    pendingCompiles.set(requestId, { resolve, reject })
    getCompilerWorker().postMessage({ type: 'compile', requestId, bundle })
  })
}

function normalizeDiagnostics(error: unknown): DemoDiagnostic[] {
  if (Array.isArray(error)) return error as DemoDiagnostic[]
  return [{ text: error instanceof Error ? error.message : String(error) }]
}

function absoluteRuntimeUrls() {
  return Object.fromEntries(
    Object.entries(runtimeUrlsValue).map(([key, value]) => [
      key,
      value ? new URL(value, window.location.origin).href : value
    ])
  ) as typeof runtimeUrlsValue
}

function languageForFile(
  file: string
): 'typescript' | 'javascript' | 'html' | 'css' | 'json' | 'plain' {
  if (/\.tsx?$/.test(file)) return 'typescript'
  if (/\.jsx?$/.test(file)) return 'javascript'
  if (file.endsWith('.vue')) return 'html'
  if (file.endsWith('.css')) return 'css'
  if (file.endsWith('.json')) return 'json'
  return 'plain'
}

const demoLang = inject<Ref<DemoLang>>('demo-lang', ref<DemoLang>('zh-CN'))
const chrome = computed(() => demoChrome(demoLang.value))
const viewport = computed(() => resolveDemoViewport(props.module.route, props.module.meta.viewport))
const moduleTitle = computed(() => demoModuleTitle(props.module.meta, demoLang.value))
const sectionRef = ref<HTMLElement | null>(null)
const iframeRef = ref<HTMLIFrameElement | null>(null)
const visible = ref(false)
const editorOpen = ref(false)
const originalBundle = ref<DemoSourceBundle | null>(null)
const files = ref<Record<string, string>>({})
const selectedFile = ref('')
const status = ref<
  'idle' | 'loading' | 'ready' | 'dirty' | 'compiling' | 'compile-error' | 'runtime-error'
>('idle')
const diagnostics = ref<DemoDiagnostic[]>([])
const consoleEntries = ref<ConsoleEntry[]>([])
const compiled = ref<DemoCompileSuccess | null>(null)
const sandbox = ref<{ channelId: string; document: string } | null>(null)
const iframeHeight = ref(viewport.value.height ?? viewport.value.minHeight)
const themeVersion = ref(0)
let latestRun = 0
let sandboxReady = false
let intersectionObserver: IntersectionObserver | null = null
let themeObserver: MutationObserver | null = null

const isDirty = computed(() => {
  if (!originalBundle.value) return false
  return Object.keys(files.value).some(
    (file) => files.value[file] !== originalBundle.value?.files[file]
  )
})
const selectedSource = computed(() => files.value[selectedFile.value] ?? '')
const sectionClasses = computed(() => (props.class ? `mb-12 ${props.class}` : 'mb-12'))
const editorTheme = computed(() =>
  typeof document !== 'undefined' && document.documentElement.classList.contains('dark')
    ? 'dark'
    : 'light'
)

function rebuildSandbox(result: DemoCompileSuccess) {
  sandboxReady = false
  const channelId = crypto.randomUUID()
  sandbox.value = {
    channelId,
    document: createSandboxDocument({
      framework: 'vue',
      meta: props.module.meta,
      js: result.js,
      css: result.css,
      imports: result.imports,
      runtimeUrls: absoluteRuntimeUrls(),
      stylesheetUrl: new URL(stylesheetUrl, window.location.origin).href,
      channelId,
      lang: demoLang.value,
      theme: ThemeManager.getCurrentTheme(),
      colorScheme: ThemeManager.getResolvedColorScheme(),
      cssVars: collectTigerCssVars(document.documentElement)
    })
  }
}

async function run(bundle: DemoSourceBundle) {
  const runId = ++latestRun
  status.value = 'compiling'
  diagnostics.value = []
  consoleEntries.value = []
  try {
    const result = await compileBundle(bundle)
    if (runId !== latestRun) return
    compiled.value = result
    rebuildSandbox(result)
  } catch (error) {
    if (runId !== latestRun) return
    diagnostics.value = normalizeDiagnostics(error)
    status.value = 'compile-error'
  }
}

async function loadAndRun() {
  if (originalBundle.value) return
  status.value = 'loading'
  try {
    const bundle = await props.module.loadSource()
    originalBundle.value = bundle
    files.value = { ...bundle.files }
    selectedFile.value = bundle.entry
    await run(bundle)
  } catch (error) {
    diagnostics.value = [{ text: error instanceof Error ? error.message : String(error) }]
    status.value = 'compile-error'
  }
}

function handleRun() {
  if (!originalBundle.value) return
  void run({ ...originalBundle.value, files: { ...files.value } })
}

function handleReset() {
  if (!originalBundle.value) return
  files.value = { ...originalBundle.value.files }
  selectedFile.value = originalBundle.value.entry
  void run({ ...originalBundle.value, files: { ...originalBundle.value.files } })
}

function updateSelectedSource(value: string) {
  files.value = { ...files.value, [selectedFile.value]: value }
  status.value = 'dirty'
}

function handleEditorKeydown(event: KeyboardEvent) {
  if ((event.metaKey || event.ctrlKey) && event.key === 'Enter') {
    event.preventDefault()
    handleRun()
  }
}

function onMessage(event: MessageEvent) {
  if (
    !sandbox.value ||
    event.source !== iframeRef.value?.contentWindow ||
    !isSandboxEvent(event.data) ||
    event.data.channelId !== sandbox.value.channelId
  ) {
    return
  }
  if (event.data.type === 'ready') {
    sandboxReady = true
    status.value = isDirty.value ? 'dirty' : 'ready'
  }
  if (event.data.type === 'runtime-error') {
    diagnostics.value = [{ text: event.data.message ?? chrome.value.runtimeFailed }]
    status.value = 'runtime-error'
  }
  if (event.data.type === 'console') {
    consoleEntries.value = [
      ...consoleEntries.value,
      { level: event.data.level ?? 'log', message: event.data.message ?? '' }
    ].slice(-100)
  }
  if (event.data.type === 'resize' && viewport.value.mode !== 'fixed') {
    const min = viewport.value.minHeight
    const next = Math.max(min, event.data.height ?? min)
    iframeHeight.value =
      viewport.value.maxHeight === undefined ? next : Math.min(viewport.value.maxHeight, next)
  }
}

onMounted(() => {
  if (sectionRef.value) {
    intersectionObserver = new IntersectionObserver(
      (entries) => {
        if (entries.some((entry) => entry.isIntersecting)) {
          visible.value = true
          intersectionObserver?.disconnect()
          void loadAndRun()
        }
      },
      { rootMargin: '500px 0px' }
    )
    intersectionObserver.observe(sectionRef.value)
  }
  themeObserver = new MutationObserver(() => themeVersion.value++)
  themeObserver.observe(document.documentElement, {
    attributes: true,
    attributeFilter: ['class', 'data-tiger-style', 'style']
  })
  window.addEventListener('message', onMessage)
})

watch([compiled, demoLang, themeVersion], ([result]) => {
  if (result && sandboxReady) rebuildSandbox(result)
})

onBeforeUnmount(() => {
  intersectionObserver?.disconnect()
  themeObserver?.disconnect()
  window.removeEventListener('message', onMessage)
})
</script>

<template>
  <section ref="sectionRef" :class="sectionClasses" :data-demo-id="module.meta.id">
    <div class="mb-4">
      <h2 class="text-2xl font-bold mb-2 dark:text-gray-100">{{ moduleTitle }}</h2>
      <p
        v-if="demoLang === 'zh-CN' && module.meta.description"
        class="text-gray-600 dark:text-gray-400">
        {{ module.meta.description }}
      </p>
    </div>

    <div
      class="overflow-hidden rounded-lg border border-gray-200 bg-gray-50 dark:border-gray-800 dark:bg-gray-950/40">
      <div class="relative bg-white dark:bg-gray-950">
        <div
          v-if="!sandbox"
          class="flex min-h-32 items-center justify-center text-sm text-gray-500"
          role="status">
          {{ status === 'compile-error' ? chrome.compileFailed : chrome.preparing }}
        </div>
        <iframe
          v-else
          ref="iframeRef"
          :title="`${moduleTitle} ${chrome.previewTitle}`"
          :srcdoc="sandbox.document"
          :sandbox="getSandboxAttribute(module.meta)"
          :allow="(module.meta.permissions ?? []).includes('fullscreen') ? 'fullscreen' : undefined"
          class="block w-full border-0 bg-transparent"
          :style="{ height: `${viewport.height ?? iframeHeight}px` }" />
      </div>

      <div
        class="flex flex-wrap items-center gap-2 border-t border-gray-200 px-3 py-2 dark:border-gray-800">
        <Button
          size="sm"
          variant="secondary"
          data-testid="demo-edit-source"
          @click="editorOpen = !editorOpen">
          {{ editorOpen ? chrome.hideSource : chrome.editSource }}
        </Button>
        <template v-if="editorOpen">
          <Button
            size="sm"
            data-testid="demo-run"
            :disabled="!originalBundle || status === 'compiling'"
            @click="handleRun">
            {{ status === 'compiling' ? chrome.compiling : chrome.run }}
          </Button>
          <Button
            size="sm"
            variant="secondary"
            data-testid="demo-reset"
            :disabled="!isDirty"
            @click="handleReset">
            {{ chrome.reset }}
          </Button>
          <Button
            size="sm"
            variant="secondary"
            data-testid="demo-copy-file"
            @click="copyTextToClipboard(selectedSource)">
            {{ chrome.copyFile }}
          </Button>
        </template>
        <span class="ml-auto text-xs text-gray-500" aria-live="polite">
          {{ isDirty && status !== 'compiling' ? chrome.dirty : status }}
        </span>
      </div>

      <div v-if="editorOpen" class="border-t border-gray-200 p-3 dark:border-gray-800">
        <div class="mb-2 flex flex-wrap gap-1" role="tablist" :aria-label="chrome.files">
          <button
            v-for="file in Object.keys(files).sort()"
            :key="file"
            type="button"
            role="tab"
            :aria-selected="selectedFile === file"
            :class="[
              'rounded px-2 py-1 text-xs',
              selectedFile === file
                ? 'bg-blue-600 text-white'
                : 'bg-gray-100 text-gray-700 dark:bg-gray-800 dark:text-gray-200'
            ]"
            @click="selectedFile = file">
            {{ file.slice(1) }}
          </button>
        </div>
        <div @keydown="handleEditorKeydown">
          <CodeEditor
            :value="selectedSource"
            :language="languageForFile(selectedFile)"
            :theme="editorTheme"
            :min-lines="8"
            :max-lines="24"
            @update:value="updateSelectedSource" />
        </div>
      </div>

      <div
        v-if="diagnostics.length > 0"
        class="border-t border-red-200 bg-red-50 p-3 text-sm text-red-700"
        role="alert">
        <div v-for="(diagnostic, index) in diagnostics" :key="`${diagnostic.text}-${index}`">
          <template v-if="diagnostic.file">
            {{ diagnostic.file }}:{{ diagnostic.line ?? 0 }}:{{ diagnostic.column ?? 0 }}
          </template>
          {{ diagnostic.text }}
        </div>
      </div>

      <details
        v-if="editorOpen && consoleEntries.length > 0"
        class="border-t border-gray-200 p-3 text-xs dark:border-gray-800">
        <summary class="cursor-pointer">
          {{ chrome.console }}（{{ consoleEntries.length }}）
        </summary>
        <pre class="mt-2 max-h-40 overflow-auto whitespace-pre-wrap">{{
          consoleEntries.map((entry) => `[${entry.level}] ${entry.message}`).join('\n')
        }}</pre>
      </details>
    </div>
  </section>
</template>

// examples/example/react/src/components/DemoBlock.tsx
import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { Button } from '@expcat/tigercat-react/Button'
import { CodeEditor } from '@expcat/tigercat-react/CodeEditor'
import { copyTextToClipboard, ThemeManager } from '@expcat/tigercat-core'
import { collectTigerCssVars } from '@demo-shared/themes'
import runtimeUrlsValue from 'virtual:tigercat-playground-runtime'
import type {
  DemoCompileResponse,
  DemoCompileSuccess,
  DemoDiagnostic,
  DemoModuleDescriptor,
  DemoSourceBundle
} from '@demo-shared/playground/types'
import {
  createSandboxDocument,
  getSandboxAttribute,
  isSandboxEvent
} from '@demo-shared/playground/sandbox'
import { demoChrome, demoModuleTitle } from '@demo-shared/chrome'
import { resolveDemoViewport } from '@demo-shared/playground/viewport'
import { useLang } from '../context/lang'
import stylesheetUrl from '@demo-shared/sandbox.css?url'

interface DemoBlockProps {
  module: DemoModuleDescriptor
  className?: string
}

interface ConsoleEntry {
  level: string
  message: string
}

let compilerWorker: Worker | null = null
let nextRequestId = 1
const pendingCompiles = new Map<
  number,
  { resolve: (result: DemoCompileSuccess) => void; reject: (diagnostics: DemoDiagnostic[]) => void }
>()

function getCompilerWorker(): Worker {
  if (compilerWorker) return compilerWorker
  compilerWorker = new Worker(new URL('../playground/compiler.worker.ts', import.meta.url), {
    type: 'module'
  })
  compilerWorker.onmessage = (event: MessageEvent<DemoCompileResponse>) => {
    const pending = pendingCompiles.get(event.data.requestId)
    if (!pending) return
    pendingCompiles.delete(event.data.requestId)
    if (event.data.type === 'compiled') pending.resolve(event.data)
    else pending.reject(event.data.diagnostics)
  }
  return compilerWorker
}

function compileBundle(bundle: DemoSourceBundle): Promise<DemoCompileSuccess> {
  const requestId = nextRequestId++
  return new Promise((resolve, reject) => {
    pendingCompiles.set(requestId, { resolve, reject })
    getCompilerWorker().postMessage({ type: 'compile', requestId, bundle })
  })
}

function normalizeDiagnostics(error: unknown): DemoDiagnostic[] {
  if (Array.isArray(error)) return error as DemoDiagnostic[]
  return [{ text: error instanceof Error ? error.message : String(error) }]
}

function absoluteRuntimeUrls() {
  return Object.fromEntries(
    Object.entries(runtimeUrlsValue).map(([key, value]) => [
      key,
      value ? new URL(value, window.location.origin).href : value
    ])
  ) as typeof runtimeUrlsValue
}

function languageForFile(file: string): 'typescript' | 'javascript' | 'css' | 'json' | 'plain' {
  if (/\.tsx?$/.test(file)) return 'typescript'
  if (/\.jsx?$/.test(file)) return 'javascript'
  if (file.endsWith('.css')) return 'css'
  if (file.endsWith('.json')) return 'json'
  return 'plain'
}

export default function DemoBlock({ module, className }: DemoBlockProps) {
  const { lang } = useLang()
  const sectionRef = useRef<HTMLElement | null>(null)
  const iframeRef = useRef<HTMLIFrameElement | null>(null)
  const latestRunRef = useRef(0)
  const sandboxReadyRef = useRef(false)
  const [visible, setVisible] = useState(false)
  const [editorOpen, setEditorOpen] = useState(false)
  const [originalBundle, setOriginalBundle] = useState<DemoSourceBundle | null>(null)
  const [files, setFiles] = useState<Record<string, string>>({})
  const [selectedFile, setSelectedFile] = useState('')
  const [status, setStatus] = useState<
    'idle' | 'loading' | 'ready' | 'dirty' | 'compiling' | 'compile-error' | 'runtime-error'
  >('idle')
  const [diagnostics, setDiagnostics] = useState<DemoDiagnostic[]>([])
  const [consoleEntries, setConsoleEntries] = useState<ConsoleEntry[]>([])
  const [compiled, setCompiled] = useState<DemoCompileSuccess | null>(null)
  const [sandbox, setSandbox] = useState<{ channelId: string; document: string } | null>(null)
  const viewport = useMemo(
    () => resolveDemoViewport(module.route, module.meta.viewport),
    [module.meta.viewport, module.route]
  )
  const [iframeHeight, setIframeHeight] = useState(viewport.height ?? viewport.minHeight)
  const chrome = demoChrome(lang)
  const [themeVersion, setThemeVersion] = useState(0)

  useEffect(() => {
    const section = sectionRef.current
    if (!section) return
    const observer = new IntersectionObserver(
      (entries) => {
        if (entries.some((entry) => entry.isIntersecting)) {
          setVisible(true)
          observer.disconnect()
        }
      },
      { rootMargin: '500px 0px' }
    )
    observer.observe(section)
    return () => observer.disconnect()
  }, [])

  useEffect(() => {
    const observer = new MutationObserver(() => setThemeVersion((value) => value + 1))
    observer.observe(document.documentElement, {
      attributes: true,
      attributeFilter: ['class', 'data-tiger-style', 'style']
    })
    return () => observer.disconnect()
  }, [])

  const isDirty = useMemo(() => {
    if (!originalBundle) return false
    return Object.keys(files).some((file) => files[file] !== originalBundle.files[file])
  }, [files, originalBundle])

  const rebuildSandbox = useCallback(
    (result: DemoCompileSuccess) => {
      sandboxReadyRef.current = false
      const channelId = crypto.randomUUID()
      setSandbox({
        channelId,
        document: createSandboxDocument({
          framework: 'react',
          meta: module.meta,
          js: result.js,
          css: result.css,
          imports: result.imports,
          runtimeUrls: absoluteRuntimeUrls(),
          stylesheetUrl: new URL(stylesheetUrl, window.location.origin).href,
          channelId,
          lang,
          theme: ThemeManager.getCurrentTheme(),
          colorScheme: ThemeManager.getResolvedColorScheme(),
          cssVars: collectTigerCssVars(document.documentElement)
        })
      })
    },
    [lang, module.meta]
  )

  const run = useCallback(
    async (bundle: DemoSourceBundle) => {
      const runId = ++latestRunRef.current
      setStatus('compiling')
      setDiagnostics([])
      setConsoleEntries([])
      try {
        const result = await compileBundle(bundle)
        if (runId !== latestRunRef.current) return
        setCompiled(result)
        rebuildSandbox(result)
      } catch (error) {
        if (runId !== latestRunRef.current) return
        setDiagnostics(normalizeDiagnostics(error))
        setStatus('compile-error')
      }
    },
    [rebuildSandbox]
  )

  useEffect(() => {
    if (!visible || originalBundle) return
    let cancelled = false
    setStatus('loading')
    module
      .loadSource()
      .then((bundle) => {
        if (cancelled) return
        setOriginalBundle(bundle)
        setFiles(bundle.files)
        setSelectedFile(bundle.entry)
        return run(bundle)
      })
      .catch((error) => {
        if (cancelled) return
        setDiagnostics([{ text: error instanceof Error ? error.message : String(error) }])
        setStatus('compile-error')
      })
    return () => {
      cancelled = true
    }
  }, [module, originalBundle, run, visible])

  useEffect(() => {
    if (compiled && sandboxReadyRef.current) rebuildSandbox(compiled)
    // themeVersion intentionally invalidates the sandbox without recompiling source.
  }, [compiled, rebuildSandbox, themeVersion])

  useEffect(() => {
    const onMessage = (event: MessageEvent) => {
      if (
        !sandbox ||
        event.source !== iframeRef.current?.contentWindow ||
        !isSandboxEvent(event.data)
      )
        return
      if (event.data.channelId !== sandbox.channelId) return
      if (event.data.type === 'ready') {
        sandboxReadyRef.current = true
        setStatus(isDirty ? 'dirty' : 'ready')
      }
      if (event.data.type === 'runtime-error') {
        setDiagnostics([{ text: event.data.message ?? chrome.runtimeFailed }])
        setStatus('runtime-error')
      }
      if (event.data.type === 'console') {
        setConsoleEntries((entries) =>
          [
            ...entries,
            { level: event.data.level ?? 'log', message: event.data.message ?? '' }
          ].slice(-100)
        )
      }
      if (event.data.type === 'resize' && viewport.mode !== 'fixed') {
        const min = viewport.minHeight
        const next = Math.max(min, event.data.height ?? min)
        setIframeHeight(
          viewport.maxHeight === undefined ? next : Math.min(viewport.maxHeight, next)
        )
      }
    }
    window.addEventListener('message', onMessage)
    return () => window.removeEventListener('message', onMessage)
  }, [chrome.runtimeFailed, isDirty, sandbox, viewport])

  const handleRun = () => {
    if (!originalBundle) return
    void run({ ...originalBundle, files })
  }

  const handleReset = () => {
    if (!originalBundle) return
    setFiles(originalBundle.files)
    setSelectedFile(originalBundle.entry)
    void run(originalBundle)
  }

  const sectionClasses = className ? `mb-12 ${className}` : 'mb-12'
  const selectedSource = files[selectedFile] ?? ''

  return (
    <section ref={sectionRef} className={sectionClasses} data-demo-id={module.meta.id}>
      <div className="mb-4">
        <h2 className="text-2xl font-bold mb-2 dark:text-gray-100">
          {demoModuleTitle(module.meta, lang)}
        </h2>
        {lang === 'zh-CN' && module.meta.description ? (
          <p className="text-gray-600 dark:text-gray-400">{module.meta.description}</p>
        ) : null}
      </div>

      <div className="overflow-hidden rounded-lg border border-gray-200 bg-gray-50 dark:border-gray-800 dark:bg-gray-950/40">
        <div className="relative bg-white dark:bg-gray-950">
          {!sandbox ? (
            <div
              className="flex min-h-32 items-center justify-center text-sm text-gray-500"
              role="status">
              {status === 'compile-error' ? chrome.compileFailed : chrome.preparing}
            </div>
          ) : (
            <iframe
              ref={iframeRef}
              title={`${demoModuleTitle(module.meta, lang)} ${chrome.previewTitle}`}
              srcDoc={sandbox.document}
              sandbox={getSandboxAttribute(module.meta)}
              allow={
                (module.meta.permissions ?? []).includes('fullscreen') ? 'fullscreen' : undefined
              }
              className="block w-full border-0 bg-transparent"
              style={{ height: viewport.height ?? iframeHeight }}
            />
          )}
        </div>

        <div className="flex flex-wrap items-center gap-2 border-t border-gray-200 px-3 py-2 dark:border-gray-800">
          <Button
            size="sm"
            variant="secondary"
            data-testid="demo-edit-source"
            onClick={() => setEditorOpen((open) => !open)}>
            {editorOpen ? chrome.hideSource : chrome.editSource}
          </Button>
          {editorOpen ? (
            <>
              <Button
                size="sm"
                data-testid="demo-run"
                onClick={handleRun}
                disabled={!originalBundle || status === 'compiling'}>
                {status === 'compiling' ? chrome.compiling : chrome.run}
              </Button>
              <Button
                size="sm"
                variant="secondary"
                data-testid="demo-reset"
                onClick={handleReset}
                disabled={!isDirty}>
                {chrome.reset}
              </Button>
              <Button
                size="sm"
                variant="secondary"
                data-testid="demo-copy-file"
                onClick={() => void copyTextToClipboard(selectedSource)}>
                {chrome.copyFile}
              </Button>
            </>
          ) : null}
          <span className="ml-auto text-xs text-gray-500" aria-live="polite">
            {isDirty && status !== 'compiling' ? chrome.dirty : status}
          </span>
        </div>

        {editorOpen ? (
          <div className="border-t border-gray-200 p-3 dark:border-gray-800">
            <div className="mb-2 flex flex-wrap gap-1" role="tablist" aria-label={chrome.files}>
              {Object.keys(files)
                .sort()
                .map((file) => (
                  <button
                    key={file}
                    type="button"
                    role="tab"
                    aria-selected={selectedFile === file}
                    className={`rounded px-2 py-1 text-xs ${
                      selectedFile === file
                        ? 'bg-blue-600 text-white'
                        : 'bg-gray-100 text-gray-700 dark:bg-gray-800 dark:text-gray-200'
                    }`}
                    onClick={() => setSelectedFile(file)}>
                    {file.slice(1)}
                  </button>
                ))}
            </div>
            <div
              onKeyDown={(event) => {
                if ((event.metaKey || event.ctrlKey) && event.key === 'Enter') {
                  event.preventDefault()
                  handleRun()
                }
              }}>
              <CodeEditor
                value={selectedSource}
                language={languageForFile(selectedFile)}
                theme={document.documentElement.classList.contains('dark') ? 'dark' : 'light'}
                minLines={8}
                maxLines={24}
                onChange={(value) => {
                  setFiles((current) => ({ ...current, [selectedFile]: value }))
                  setStatus('dirty')
                }}
              />
            </div>
          </div>
        ) : null}

        {diagnostics.length > 0 ? (
          <div className="border-t border-red-200 bg-red-50 p-3 text-sm text-red-700" role="alert">
            {diagnostics.map((diagnostic, index) => (
              <div key={`${diagnostic.text}-${index}`}>
                {diagnostic.file
                  ? `${diagnostic.file}:${diagnostic.line ?? 0}:${diagnostic.column ?? 0} `
                  : ''}
                {diagnostic.text}
              </div>
            ))}
          </div>
        ) : null}

        {editorOpen && consoleEntries.length > 0 ? (
          <details className="border-t border-gray-200 p-3 text-xs dark:border-gray-800">
            <summary className="cursor-pointer">
              {chrome.console}（{consoleEntries.length}）
            </summary>
            <pre className="mt-2 max-h-40 overflow-auto whitespace-pre-wrap">
              {consoleEntries.map((entry) => `[${entry.level}] ${entry.message}`).join('\n')}
            </pre>
          </details>
        ) : null}
      </div>
    </section>
  )
}
