// examples/example/react/src/pages/ColorPickerDemo.tsx
import { Space } from '@expcat/tigercat-react/Space'
import { Text } from '@expcat/tigercat-react/Text'
import { useState } from 'react'
import { ColorPicker } from '@expcat/tigercat-react/ColorPicker'
import DemoBlock from '../components/DemoBlock'
import fullPageSnippet from './ColorPickerDemo.tsx?raw'

const basicSnippet = `<ColorPicker value={color} onChange={setColor} />
<Text>选中颜色: {color}</Text>`

const basicScriptSnippet = `import { useState } from 'react'

const [color, setColor] = useState('#2563eb')`

const featureSnippet = `<ColorPicker value={color} onChange={setColor} showAlpha format="rgb" />
<ColorPicker value={color} onChange={setColor} presets={['#f5222d', '#fa8c16', '#52c41a', '#1677ff', '#722ed1']} />
<ColorPicker value="#ccc" size="sm" />
<ColorPicker value="#ccc" size="lg" />
<ColorPicker value="#ccc" disabled />`

const ColorPickerDemo: React.FC = () => {
  const [color, setColor] = useState('#2563eb')
  const [color2, setColor2] = useState('#2563eb')

  return (
    <div className="max-w-5xl mx-auto p-4 sm:p-8">
      <h1 className="text-3xl font-bold mb-2">ColorPicker 颜色选择器</h1>
      <p className="text-gray-500 mb-8">用于选择颜色，支持透明度、预设颜色和多种格式。</p>

      <DemoBlock title="基本用法" code={fullPageSnippet}>
        <Space size={16} align="center">
          <ColorPicker value={color} onChange={setColor} />
          <Text>选中颜色: {color}</Text>
        </Space>
      </DemoBlock>

      <DemoBlock
        title="透明度、预设与尺寸"
        description="showAlpha 透明度，presets 预设色板"
        code={fullPageSnippet}>
        <Space direction="vertical" size={12}>
          <ColorPicker value={color2} onChange={setColor2} showAlpha format="rgb" />
          <ColorPicker
            value={color2}
            onChange={setColor2}
            presets={['#f5222d', '#fa8c16', '#52c41a', '#1677ff', '#722ed1']}
          />
          <Space size={12}>
            <ColorPicker value="#ccc" size="sm" />
            <ColorPicker value="#ccc" size="lg" />
            <ColorPicker value="#ccc" disabled />
          </Space>
        </Space>
      </DemoBlock>
    </div>
  )
}

export default ColorPickerDemo

// examples/example/vue3/src/pages/ColorPickerDemo.vue
<script setup lang="ts">
import { Space } from '@expcat/tigercat-vue/Space'
import { Text } from '@expcat/tigercat-vue/Text'
import { ref } from 'vue'
import { ColorPicker } from '@expcat/tigercat-vue/ColorPicker'
import DemoBlock from '../components/DemoBlock.vue'
import fullPageSnippet from './ColorPickerDemo.vue?raw'

const color = ref('#2563eb')
const color2 = ref('#2563eb')

const basicScriptSnippet = `import { ref } from 'vue'

const color = ref('#2563eb')`

const basicSnippet = `<ColorPicker v-model="color" />
<Text>选中颜色: {{ color }}</Text>`

const featureSnippet = `<Space direction="vertical" :size="12">
  <ColorPicker v-model="color" show-alpha format="rgb" />
  <ColorPicker v-model="color" :presets="['#f5222d', '#fa8c16', '#52c41a', '#1677ff', '#722ed1']" />
  <ColorPicker :model-value="'#ccc'" size="sm" />
  <ColorPicker :model-value="'#ccc'" size="lg" />
  <ColorPicker :model-value="'#ccc'" disabled />
</Space>`
</script>

<template>
  <div class="max-w-5xl mx-auto p-4 sm:p-8">
    <h1 class="text-3xl font-bold mb-2">ColorPicker 颜色选择器</h1>
    <p class="text-gray-500 mb-8">用于选择颜色，支持透明度、预设颜色和多种格式。</p>

    <DemoBlock title="基本用法" :code="fullPageSnippet">
      <Space :size="16" align="center">
        <ColorPicker v-model="color" />
        <Text>选中颜色: {{ color }}</Text>
      </Space>
    </DemoBlock>

    <DemoBlock
      title="透明度、预设与尺寸"
      description="showAlpha 透明度，presets 预设色板"
      :code="fullPageSnippet">
      <Space direction="vertical" :size="12">
        <ColorPicker v-model="color2" show-alpha format="rgb" />
        <ColorPicker
          v-model="color2"
          :presets="['#f5222d', '#fa8c16', '#52c41a', '#1677ff', '#722ed1']" />
        <Space :size="12">
          <ColorPicker :model-value="'#ccc'" size="sm" />
          <ColorPicker :model-value="'#ccc'" size="lg" />
          <ColorPicker :model-value="'#ccc'" disabled />
        </Space>
      </Space>
    </DemoBlock>
  </div>
</template>
