// examples/example/react/src/pages/Home.tsx
import React from 'react'
import { Code } from '@expcat/tigercat-react/Code'

const Home: React.FC = () => {
  return (
    <div className="max-w-5xl">
      <div className="mb-6">
        <h1 className="text-3xl font-bold text-gray-900 dark:text-gray-100">
          如何在项目中使用 Tigercat（React）
        </h1>
        <p className="mt-2 text-gray-600 dark:text-gray-300">按照下面的步骤安装并使用组件库。</p>
      </div>

      <div className="mb-6">
        <div className="rounded-lg border border-(--tiger-primary,#2563eb)/40 bg-(--tiger-primary,#2563eb)/5 p-4">
          <div className="flex items-center gap-2 mb-1">
            <span className="text-base">⚛️</span>
            <span className="text-sm font-semibold text-(--tiger-primary,#2563eb)">
              当前框架 · React
            </span>
          </div>
          <p className="text-sm text-gray-600 dark:text-gray-300">
            基于 <code>@expcat/tigercat-react</code>，与 React 19 + ConfigProvider 深度集成。
          </p>
        </div>
      </div>

      <div className="mt-6 space-y-6">
        <section>
          <h2 className="text-lg font-semibold text-gray-900 dark:text-gray-100">1. 安装</h2>
          <Code className="mt-3" code="pnpm add @expcat/tigercat-react @expcat/tigercat-core" />
        </section>

        <section>
          <h2 className="text-lg font-semibold text-gray-900 dark:text-gray-100">
            2. 配置 Tailwind
          </h2>
          <p className="mt-2 text-sm text-gray-600 dark:text-gray-400">
            在 <code>tailwind.config.js</code> 中添加插件与扫描路径：
          </p>
          <Code
            className="mt-3"
            code={`// tailwind.config.js
import { tigercatPlugin } from '@expcat/tigercat-core'

export default {
  content: [
    // ...
    './node_modules/@expcat/tigercat-*/dist/**/*.{js,mjs}'
  ],
  plugins: [
    tigercatPlugin
  ]
}`}
          />
        </section>

        <section>
          <h2 className="text-lg font-semibold text-gray-900 dark:text-gray-100">
            3. 引入样式入口
          </h2>
          <p className="mt-2 text-sm text-gray-600 dark:text-gray-400">
            在项目的 CSS 文件中加入以下内容（放在业务样式之前）：
          </p>
          <Code
            className="mt-3"
            code={`@import 'tailwindcss';
@source '../node_modules/@expcat/tigercat-react/dist/**/*.{js,mjs}';
@source '../node_modules/@expcat/tigercat-core/dist/**/*.{js,mjs}';`}
          />
        </section>

        <section>
          <h2 className="text-lg font-semibold text-gray-900 dark:text-gray-100">4. 组件使用</h2>

          <Code
            className="mt-3"
            code={`import { Button } from '@expcat/tigercat-react/Button'
import { ConfigProvider } from '@expcat/tigercat-react/ConfigProvider'

function App() {
  return (
    <ConfigProvider>
      <Button variant="primary">开始使用</Button>
    </ConfigProvider>
  )
}
`}
          />
        </section>

        <section>
          <h2 className="text-lg font-semibold text-gray-900 dark:text-gray-100">
            5. 主题色（可选）
          </h2>

          <Code
            className="mt-3"
            code={`:root {
  --tiger-primary: #2563eb;
  --tiger-primary-hover: #1d4ed8;
}`}
          />
        </section>
      </div>
    </div>
  )
}

export default Home

// examples/example/vue3/src/pages/Home.vue
<script setup lang="ts">
import { Code } from '@expcat/tigercat-vue/Code'

const installSnippet = 'pnpm add @expcat/tigercat-vue @expcat/tigercat-core'
const scriptClose = '</scr' + 'ipt>'

const configSnippet = `// tailwind.config.js
import { tigercatPlugin } from '@expcat/tigercat-core'

export default {
  content: [
    // ...
    './node_modules/@expcat/tigercat-*/dist/**/*.{js,mjs}'
  ],
  plugins: [
    tigercatPlugin
  ]
}`

const cssSnippet = `@import 'tailwindcss';
@source '../node_modules/@expcat/tigercat-vue/dist/**/*.{js,mjs}';
@source '../node_modules/@expcat/tigercat-core/dist/**/*.{js,mjs}';`

const usageSnippet = [
  '<script setup lang="ts">',
  "import { Button } from '@expcat/tigercat-vue/Button'",
  "import { ConfigProvider } from '@expcat/tigercat-vue/ConfigProvider'",
  scriptClose,
  '',
  '<template>',
  '  <ConfigProvider>',
  '    <Button variant="primary">开始使用</Button>',
  '  </ConfigProvider>',
  '</template>'
].join('\n')

const themeSnippet = `:root {
  --tiger-primary: #2563eb;
  --tiger-primary-hover: #1d4ed8;
}`
</script>

<template>
  <div class="max-w-5xl">
    <div class="mb-6">
      <h1 class="text-3xl font-bold text-gray-900 dark:text-gray-100">
        如何在项目中使用 Tigercat（Vue 3）
      </h1>
      <p class="mt-2 text-gray-600 dark:text-gray-300">按照下面的步骤安装并使用组件库。</p>
    </div>

    <div class="mb-6">
      <div
        class="rounded-lg border border-(--tiger-primary,#2563eb)/40 bg-(--tiger-primary,#2563eb)/5 p-4">
        <div class="flex items-center gap-2 mb-1">
          <span class="text-base">🟢</span>
          <span class="text-sm font-semibold text-(--tiger-primary,#2563eb)">当前框架 · Vue 3</span>
        </div>
        <p class="text-sm text-gray-600 dark:text-gray-300">
          基于 <code>@expcat/tigercat-vue</code>，与 Vue 3.5 + ConfigProvider 深度集成。
        </p>
      </div>
    </div>

    <div class="mt-6 space-y-6">
      <section>
        <h2 class="text-lg font-semibold text-gray-900 dark:text-gray-100">1. 安装</h2>
        <Code class="mt-3" :code="installSnippet" />
      </section>

      <section>
        <h2 class="text-lg font-semibold text-gray-900 dark:text-gray-100">2. 配置 Tailwind</h2>
        <p class="mt-2 text-sm text-gray-600 dark:text-gray-400">
          在 <code>tailwind.config.js</code> 中添加插件与扫描路径：
        </p>
        <Code class="mt-3" :code="configSnippet" />
      </section>

      <section>
        <h2 class="text-lg font-semibold text-gray-900 dark:text-gray-100">3. 引入样式入口</h2>
        <p class="mt-2 text-sm text-gray-600 dark:text-gray-400">
          在项目的 CSS 文件中加入以下内容（放在业务样式之前）：
        </p>
        <Code class="mt-3" :code="cssSnippet" />
      </section>

      <section>
        <h2 class="text-lg font-semibold text-gray-900 dark:text-gray-100">4. 组件使用</h2>

        <Code class="mt-3" :code="usageSnippet" />
      </section>

      <section>
        <h2 class="text-lg font-semibold text-gray-900 dark:text-gray-100">5. 主题色（可选）</h2>
        <Code class="mt-3" :code="themeSnippet" />
      </section>
    </div>
  </div>
</template>
