// examples/example/react/src/pages/LineChartDemo.tsx
import DemoPage from '../components/DemoPage'
import { getDemoModules } from '../playground/registry'

const modules = getDemoModules('line-chart')

export default function LineChartDemo() {
  return (
    <DemoPage
      title="LineChart 折线图"
      description="用于展示数据随时间或类别变化趋势。"
      modules={modules}
    />
  )
}

// examples/example/vue3/src/pages/LineChartDemo.vue
<script setup lang="ts">
import DemoPage from '../components/DemoPage.vue'
import { getDemoModules } from '../playground/registry'

// LineChartDemo
const modules = getDemoModules('line-chart')
</script>

<template>
  <DemoPage
    title="LineChart 折线图"
    description="用于展示数据随时间或类别变化趋势。"
    :modules="modules" />
</template>
