// examples/example/react/src/pages/SelectDemo.tsx
import DemoPage from '../components/DemoPage'
import { getDemoModules } from '../playground/registry'

const modules = getDemoModules('select')

export default function SelectDemo() {
  return (
    <DemoPage
      title="Select 选择器"
      description="当选项过多时，使用下拉菜单展示并选择内容。"
      modules={modules}
    />
  )
}

// examples/example/vue3/src/pages/SelectDemo.vue
<script setup lang="ts">
import DemoPage from '../components/DemoPage.vue'
import { getDemoModules } from '../playground/registry'

// SelectDemo
const modules = getDemoModules('select')
</script>

<template>
  <DemoPage
    title="Select 选择器"
    description="当选项过多时，使用下拉菜单展示并选择内容。"
    :modules="modules" />
</template>
