// examples/example/react/src/pages/UseDragDemo.tsx
import React, { useState } from 'react'
import { Card } from '@expcat/tigercat-react/Card'
import { Tag } from '@expcat/tigercat-react/Tag'
import { useDrag } from '@expcat/tigercat-react'
import type { DragItem } from '@expcat/tigercat-core'
import DemoBlock from '../components/DemoBlock'
import fullPageSnippet from './UseDragDemo.tsx?raw'

interface TodoItem extends DragItem {
  title: string
}

const initialItems: TodoItem[] = [
  { id: '1', index: 0, title: '编写需求文档' },
  { id: '2', index: 1, title: '完成接口联调' },
  { id: '3', index: 2, title: '进行单元测试' },
  { id: '4', index: 3, title: '上线灰度发布' }
]

const UseDragDemo: React.FC = () => {
  const [items, setItems] = useState<TodoItem[]>(initialItems)

  const drag = useDrag({
    onDrop: () => {
      const result = drag.reorder(items)
      if (result) {
        setItems(result.items.map((item, index) => ({ ...item, index })))
      }
    }
  })

  const draggedTitle = drag.draggedItem
    ? (items.find((it) => it.id === drag.draggedItem!.id)?.title ?? '无')
    : '无'

  return (
    <div className="max-w-5xl mx-auto p-4 sm:p-8">
      <div className="mb-8">
        <h1 className="text-3xl font-bold mb-2">useDrag 拖拽</h1>
        <p className="text-gray-600 dark:text-gray-400">
          框架无关的拖拽逻辑封装，提供 <code>getDragItemProps</code> / <code>getDropZoneProps</code>{' '}
          来快速绑定 HTML 拖拽事件。
        </p>
      </div>

      <DemoBlock
        title="基础列表排序"
        description="拖动条目即可重新排序，松开时通过 reorder() 计算新顺序。"
        code={fullPageSnippet}>
        <div className="space-y-3" {...drag.getDropZoneProps()}>
          {items.map((item) => (
            <Card
              key={item.id}
              {...drag.getDragItemProps(item)}
              className="cursor-move select-none">
              <div className="flex items-center justify-between">
                <span>{item.title}</span>
                <Tag color="blue">序号 {item.index + 1}</Tag>
              </div>
            </Card>
          ))}
        </div>
        <div className="mt-4 text-sm text-gray-500">
          当前拖拽：<strong>{draggedTitle}</strong>
        </div>
      </DemoBlock>
    </div>
  )
}

export default UseDragDemo

// examples/example/vue3/src/pages/UseDragDemo.vue
<script setup lang="ts">
import { Card } from '@expcat/tigercat-vue/Card'
import { Tag } from '@expcat/tigercat-vue/Tag'
import { ref, computed } from 'vue'
import { useDrag } from '@expcat/tigercat-vue'
import type { DragItem } from '@expcat/tigercat-core'
import DemoBlock from '../components/DemoBlock.vue'
import fullPageSnippet from './UseDragDemo.vue?raw'

interface TodoItem extends DragItem {
  title: string
}

const items = ref<TodoItem[]>([
  { id: '1', index: 0, title: '编写需求文档' },
  { id: '2', index: 1, title: '完成接口联调' },
  { id: '3', index: 2, title: '进行单元测试' },
  { id: '4', index: 3, title: '上线灰度发布' }
])

const drag = useDrag({
  onDrop: () => {
    const result = drag.reorder(items.value)
    if (result) {
      items.value = result.items.map((item, index) => ({ ...item, index }))
    }
  }
})

const draggedTitle = computed(() => {
  const id = drag.draggedItem.value?.id
  return id ? (items.value.find((it) => it.id === id)?.title ?? '无') : '无'
})
</script>

<template>
  <div class="max-w-5xl mx-auto p-4 sm:p-8">
    <div class="mb-8">
      <h1 class="text-3xl font-bold mb-2">useDrag 拖拽</h1>
      <p class="text-gray-600 dark:text-gray-400">
        框架无关的拖拽逻辑封装，提供 <code>getDragItemAttrs</code> /
        <code>getDropZoneAttrs</code> 来快速绑定 HTML 拖拽事件。
      </p>
    </div>

    <DemoBlock
      title="基础列表排序"
      description="拖动条目即可重新排序，松开时通过 reorder() 计算新顺序。"
      :code="fullPageSnippet">
      <div class="space-y-3" v-bind="drag.getDropZoneAttrs()">
        <Card
          v-for="item in items"
          :key="item.id"
          v-bind="drag.getDragItemAttrs(item)"
          class="cursor-move select-none">
          <div class="flex items-center justify-between">
            <span>{{ item.title }}</span>
            <Tag color="blue">序号 {{ item.index + 1 }}</Tag>
          </div>
        </Card>
      </div>
      <div class="mt-4 text-sm text-gray-500">
        当前拖拽：<strong>{{ draggedTitle }}</strong>
      </div>
    </DemoBlock>
  </div>
</template>
