// examples/example/react/src/components/LanguageSwitch.tsx
import React from 'react'
import { Select } from '@expcat/tigercat-react/Select'
import { DEMO_LANG_OPTIONS, isDemoLang, type DemoLang } from '@demo-shared/app-config'
import { demoChrome } from '@demo-shared/chrome'

const languageOptions = DEMO_LANG_OPTIONS.map((o) => ({ label: o.label, value: o.value }))

export interface LanguageSwitchProps {
  value: DemoLang
  onChange: (lang: DemoLang) => void
}

export const LanguageSwitch: React.FC<LanguageSwitchProps> = ({ value, onChange }) => {
  const handleChange = (next: string | number | (string | number)[] | undefined) => {
    const v = Array.isArray(next) ? next[0] : next
    if (isDemoLang(v)) onChange(v)
  }

  return (
    <div className="flex items-center gap-2 shrink-0">
      <span className="text-sm font-medium text-gray-700 whitespace-nowrap shrink-0 dark:text-gray-200">
        {demoChrome(value).language}
      </span>
      <Select
        value={value}
        onChange={handleChange}
        options={languageOptions}
        size="sm"
        className="w-28 max-w-full"
      />
    </div>
  )
}

export default LanguageSwitch

// examples/example/vue3/src/components/LanguageSwitch.vue
<script setup lang="ts">
import { Select } from '@expcat/tigercat-vue/Select'
import { DEMO_LANG_OPTIONS, isDemoLang, type DemoLang } from '@demo-shared/app-config'
import { demoChrome } from '@demo-shared/chrome'

const props = defineProps<{ modelValue: DemoLang }>()
const emit = defineEmits<{ (e: 'update:modelValue', v: DemoLang): void }>()

const options = DEMO_LANG_OPTIONS.map((o) => ({ label: o.label, value: o.value }))

const handleChange = (value: string) => {
  if (isDemoLang(value)) emit('update:modelValue', value)
}
</script>

<template>
  <div class="flex items-center gap-2 shrink-0">
    <span class="text-sm font-medium text-gray-700 whitespace-nowrap shrink-0 dark:text-gray-200">
      {{ demoChrome(props.modelValue).language }}
    </span>
    <Select
      :model-value="props.modelValue"
      @update:model-value="handleChange"
      :options="options"
      size="sm"
      class="w-28 max-w-full" />
  </div>
</template>
